name: fluffychat
description: A convenient Matrix-based tool for personal and corporate communication.
publish_to: none
version: 2.6.14+2330

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:

  ### Dependencies from git ###
  matrix:
    git:
      url: git@github.com:linagora/matrix-dart-sdk.git
      ref: twake-supported-0.22.6

  receive_sharing_intent:
    git:
      url: https://github.com/linagora/receive_sharing_intent.git
      ref: master

  # TODO: Android native lib build error: https://github.com/jonataslaw/VideoCompress/issues/240
  # video_compress: ^3.1.1
  video_compress:
    git:
      url: git@github.com:SpectoraSoftware/VideoCompress.git
      ref: master

  linagora_design_flutter:
    git:
      url: git@github.com:linagora/linagora-design-flutter.git
      ref: master
  flutter_matrix_html:
    git:
      url: https://github.com/linagora/flutter_matrix_html.git
      ref: master

  contacts_service:
    git:
      url: git@github.com:linagora/flutter_contacts.git
      ref: master

  # TODO: Remove it after this PR merged
  # https://github.com/justsoft/video_thumbnail/pull/135
  video_thumbnail:
    git:
      url: https://github.com/maRci002/video_thumbnail.git
      ref: feat-web_implementation
      path: video_thumbnail

  # TODO: We will change it when the PR in upstream repository will be merged
  # https://github.com/rvamsikrishna/inview_notifier_list/pull/60
  inview_notifier_list:
    git:
      url: git@github.com:linagora/inview_notifier_list.git
      ref: master

  future_loading_dialog:
    git:
      url: git@github.com:linagora/future-loading-dialog.git
      ref: main

  linkfy_text:
    git:
      url: git@github.com:linagora/linkfy_text.git
      ref: main

  adaptive_dialog: ^1.8.0+1
  flutter_adaptive_scaffold: ^0.1.4
  animations: ^2.0.7
  blurhash_dart: ^1.1.0
  # TODO: remove it after it release a new version, the PR is merged to master
  callkeep: 
    git:
      url: https://github.com/flutter-webrtc/callkeep
      ref: master
  chewie: ^1.3.6
  collection: ^1.16.0
  connectivity_plus: ^3.0.2
  cupertino_icons: any
  desktop_drop: ^0.4.4
  desktop_lifecycle: ^0.1.0
  desktop_notifications: ^0.6.3
  device_info_plus: ^10.1.0
  dynamic_color: ^1.6.0
  emoji_picker_flutter: ^1.5.1
  emoji_proposal: ^0.0.1
  emojis: ^0.9.9
  # TODO: remove this after this PR is merged https://gitlab.com/famedly/company/frontend/libraries/native_imaging/-/merge_requests/22
  fcm_shared_isolate:
    git:
      url: https://github.com/famedly/fcm_shared_isolate.git
      ref: main
  file_picker: ^8.0.5
  flutter:
    sdk: flutter
  # TODO: remove this after this PR is merged https://github.com/g123k/flutter_app_badger/pull/92
  flutter_app_badger:
    git:
      url: https://github.com/bitsydarel/flutter_app_badger.git
      ref: master
  flutter_app_lock: ^3.0.0
  flutter_blurhash: ^0.8.2
  flutter_cache_manager: ^3.3.0
  flutter_foreground_task: ^3.10.0
  flutter_local_notifications: 17.2.2
  flutter_localizations:
    sdk: flutter
  flutter_map: ^4.0.0
  #  flutter_matrix_html: ^1.1.0
  flutter_olm: ^1.2.0
  flutter_openssl_crypto: ^0.3.0
  flutter_ringtone_player: 4.0.0+3
  flutter_secure_storage: ^9.2.1
  flutter_svg: ^0.22.0
  flutter_typeahead: ^5.1.0
  flutter_web_auth_2: ^3.1.1
  # flutter_webrtc: # Until https://github.com/flutter-webrtc/flutter-webrtc/issues/1212 is fixed
  #   git: https://github.com/radzio-it/flutter-webrtc.git
  flutter_webrtc: ^0.10.6
  handy_window: ^0.1.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.4
  image: ^4.0.15
  image_picker: ^1.0.4
  intl: any
  just_audio: ^0.9.30
  just_audio_mpv: ^0.1.6
  keyboard_shortcuts: ^0.1.4
  latlong2: ^0.8.1
  matrix_homeserver_recommendations: ^0.3.0
  matrix_link_text: ^2.0.0
  # TODO: remove this after this PR is merged https://gitlab.com/famedly/company/frontend/libraries/native_imaging/-/merge_requests/22
  native_imaging: 
    git:
      url: https://github.com/famedly/dart_native_imaging
      ref: main
  package_info_plus: ^8.0.0
  path_provider: ^2.0.15
  permission_handler: ^11.0.1
  pin_code_text_field: ^1.8.0
  provider: ^6.0.2
  punycode: ^1.0.0
  qr_code_scanner: ^1.0.0
  qr_flutter: ^4.0.0
  record: ^4.4.4
  scroll_to_index: ^3.0.1
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  slugify: ^2.0.0
  skeletons:
    # TODO: Remove when https://github.com/badjio/skeletons/pull/9 is merged
    git:
      url: https://github.com/alirezat66/skeletons.git
      ref: master
  tor_detector_web: ^1.1.0
  app_links: ^6.2.0
  unifiedpush: ^5.0.1 
  universal_html: ^2.0.8
  url_launcher: ^6.0.20
  vibration: ^1.7.4-nullsafety.0
  go_router: ^14.1.2
  wakelock: ^0.6.2
  webrtc_interface: ^1.0.10
  overflow_view: ^0.3.1
  json_annotation: 4.9.0
  equatable: ^2.0.5
  get_it: ^7.2.0
  dio: ^5.1.1
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_hive_store: ^3.2.1
  dartz: ^0.10.1
  debounce_throttle: ^2.0.0
  fluttertoast: ^8.2.2
  rxdart: ^0.27.7
  photo_manager: ^3.0.0-dev.5
  flutter_inappwebview: ^6.0.0
  tuple: ^2.0.2
  lottie: ^3.0.0
  wechat_camera_picker: 4.2.2
  open_file: ^3.3.2
  mime: ^1.0.4
  async: ^2.11.0
  cached_network_image: ^3.2.3
  flutter_image_compress: ^2.0.4
  # TODO: remove when https://github.com/hui-z/image_gallery_saver/pull/310 is merged
  image_gallery_saver:
    git:
      url: https://github.com/FlutterStudioIst/image_gallery_saver.git
      ref: master
  file_saver: ^0.2.12
  flutter_keyboard_visibility: ^6.0.0
  media_kit: ^1.1.7
  media_kit_video: ^1.1.8
  media_kit_libs_video: ^1.0.1
  video_player: ^2.7.2
  js: ^0.6.7
  super_clipboard: 0.8.15
  crypto: ^3.0.3
  flutter_contacts: ^1.1.7+1
  flutter_localized_locales: ^2.0.5
  after_layout: ^1.2.0
  photo_manager_image_provider: ^2.1.0
  flutter_slidable: ^3.0.1
  skeletonizer: 1.1.2+1
  flutter_portal: 1.1.4
  external_path: 1.0.3
  gal: 2.3.0
  auto_size_text: 3.0.0
  flutter_avif: 2.4.1
  heif_converter: 1.0.0
  pull_down_button: 0.10.2
  pretty_qr_code: 3.3.0

dev_dependencies:
  build_runner: 2.4.12
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  flutter_native_splash: ^2.0.3+1
  flutter_test:
    sdk: flutter
  hive_generator: 2.0.1
  import_sorter: ^4.6.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.6.2
  msix: ^3.6.2
  translations_cleaner: ^0.0.5
  mockito: 5.4.4


flutter_launcher_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon_launcher.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/icon_launcher.png"

flutter_native_splash:
  color: "#000000"
  image: "assets/logo.png"
  branding: "assets/branding.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/sounds/
    - assets/js/
    - assets/js/package/
    - assets/google_fonts/
    - configurations/
    - configurations/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/google_fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Inter-Bold.ttf
          weight: 700

msix_config:
  display_name: Twake Chat
  publisher_display_name: Twake Chat
  publisher: CN=Twake, O=Linagora, C=FR
  identity_name: app.twake.windows.chat
  logo_path: assets\logo.png
  capabilities: internetClient, location, microphone, webcam
  protocol_activation: https
  app_uri_handler_hosts: matrix.to
  execution_alias: twake
  sign_msix: true
  install_certificate: false

dependency_overrides:
  # Until all dependencies are compatible. Missing: file_picker_cross, flutter_matrix_html
  ffi: 2.0.0
  http: 1.2.1
  # This otherwise breaks on linux with flutter 3.7.0, let's override it for now.
  file_selector: ^0.9.2+2
  file_selector_linux: ^0.9.1
  flutter_svg: ^2.0.4
  # fake secure storage plugin for Windows
  # See: https://gitlab.com/gitlab-com/gl-infra/reliability/-/issues/15161
  flutter_secure_storage_windows:
    git:
      url: https://gitlab.com/TheOneWithTheBraid/flutter_secure_storage_windows.git
      ref: main
  geolocator_android: 4.6.1
  # waiting for null safety
  # Upstream pull request: https://github.com/AntoineMarcel/keyboard_shortcuts/pull/13
  keyboard_shortcuts:
    git:
      url: https://github.com/TheOneWithTheBraid/keyboard_shortcuts.git
      ref: null-safety
  # blocked upgrade of package_info_plus for null safety
  # https://github.com/creativecreatorormaybenot/wakelock/pull/203
  wakelock_windows:
    git:
      url: https://github.com/chandrabezzo/wakelock.git
      ref: main
      path: wakelock_windows/
  # TODO: Remove this part after upstream contribution is merged
  # https://github.com/Sorunome/matrix_link_text/pull/4
  # https://github.com/Sorunome/matrix_link_text/pull/5
  matrix_link_text:
    git:
      url: https://github.com/linagora/matrix_link_text.git
      ref: twake-supported
  # TODO: Remove this part when update matrix_homeserver_recommendations to same version as matrix_dart_sdk
  matrix_api_lite:
    git:
      url: https://github.com/linagora/dart_matrix_api_lite.git
      ref: main

cider:
  link_template:
    tag: https://github.com/linagora/twake-on-matrix/releases/tag/%tag% # initial release link template