name: fluffychat
description: The open digital workplace.
publish_to: none
version: 2.1.4+2330

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  adaptive_dialog: ^1.8.0+1
  animations: ^2.0.7
  badges: ^2.0.3
  blurhash_dart: ^1.1.0
  callkeep: ^0.3.2
  chewie: ^1.3.6
  collection: ^1.16.0
  connectivity_plus: ^3.0.2
  cupertino_icons: any
  desktop_drop: ^0.4.0
  desktop_lifecycle: ^0.1.0
  desktop_notifications: ^0.6.3
  device_info_plus: ^8.0.0
  dynamic_color: ^1.6.0
  emoji_picker_flutter: ^1.5.1
  emoji_proposal: ^0.0.1
  emojis: ^0.9.9
  fcm_shared_isolate: ^0.1.0
  file_picker_cross: ^4.6.0
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_app_lock: ^3.0.0
  flutter_blurhash: ^0.7.0
  flutter_cache_manager: ^3.3.0
  flutter_foreground_task: ^3.10.0
  flutter_local_notifications: ^12.0.2
  flutter_localizations:
    sdk: flutter
  flutter_map: ^3.1.0
#  flutter_matrix_html: ^1.1.0
  flutter_olm: ^1.2.0
  flutter_openssl_crypto: ^0.1.0
  flutter_ringtone_player: ^3.1.1
  flutter_secure_storage: ^7.0.1
  flutter_svg: ^0.22.0
  flutter_typeahead: ^4.3.2
  flutter_web_auth: ^0.5.0
  # flutter_webrtc: # Until https://github.com/flutter-webrtc/flutter-webrtc/issues/1212 is fixed
  #   git: https://github.com/radzio-it/flutter-webrtc.git
  flutter_webrtc:
    git: https://github.com/flutter-webrtc/flutter-webrtc.git
  future_loading_dialog: ^0.2.3
  geolocator: ^7.6.2
  handy_window: ^0.1.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.4
  image: ^3.1.1
  image_picker: ^0.8.4+8
  intl: any
  just_audio: ^0.9.30
  just_audio_mpv: ^0.1.6
  keyboard_shortcuts: ^0.1.4
  latlong2: ^0.8.1
  matrix: ^0.18.0
  matrix_homeserver_recommendations: ^0.3.0
  matrix_link_text: ^1.0.2
  native_imaging: ^0.1.0
  package_info_plus: ^1.3.0
  path_provider: ^2.0.9
  permission_handler: ^10.2.0
  pin_code_text_field: ^1.8.0
  provider: ^6.0.2
  punycode: ^1.0.0
  qr_code_scanner: ^1.0.0
  qr_flutter: ^4.0.0
  receive_sharing_intent: ^1.4.5
  record: ^4.4.4
  scroll_to_index: ^3.0.1
  share_plus: ^4.0.10+1
  shared_preferences: 2.0.15 # Pinned because https://github.com/flutter/flutter/issues/118401
  slugify: ^2.0.0
  skeletons: ^0.0.3
  swipe_to_action: ^0.2.0
  tor_detector_web: ^1.1.0
  uni_links: ^0.5.1
  unifiedpush: ^4.0.3
  universal_html: ^2.0.8
  url_launcher: ^6.0.20
  vibration: ^1.7.4-nullsafety.0
  # TO DO: Android native lib build error: https://github.com/jonataslaw/VideoCompress/issues/240
  # video_compress: ^3.1.1
  video_compress:
    git:
      url: git@github.com:SpectoraSoftware/VideoCompress.git
      ref: master
  video_player: ^2.2.18
  vrouter: ^1.2.0+21
  wakelock: ^0.6.1+1
  webrtc_interface: ^1.0.10
  linagora_design_flutter:
    git:
      url: git@github.com:linagora/linagora-design-flutter.git
      ref: master
  flutter_matrix_html:
    git:
      url: git@github.com:linagora/flutter_matrix_html.git
      ref: master
  overflow_view: ^0.3.1
  json_annotation: ^4.8.1
  contacts_service:
    git:
      url: git@github.com:linagora/flutter_contacts.git
      ref: master
  equatable: ^2.0.5
  get_it: ^7.2.0
  dio: ^5.1.1
  dartz: ^0.10.1
  debounce_throttle: ^2.0.0
  fluttertoast: ^8.2.2
  rxdart: ^0.27.7
  photo_manager: ^2.6.0
  flutter_inappwebview: ^5.7.2+3
  tuple: ^2.0.2
  lottie: ^2.3.2
dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.3
  flutter_launcher_icons: 0.11.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.0.3+1
  flutter_test:
    sdk: flutter
  hive_generator: 2.0.0
  import_sorter: ^4.6.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.6.2
  msix: ^3.6.2
  translations_cleaner: ^0.0.5

flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon_launcher.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/icon_launcher.png"

flutter_native_splash:
  color: "#000000"
  image: "assets/info-logo.png"
  branding: "assets/branding.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/sounds/
    - assets/js/
    - assets/js/package/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: RobotoMono
      fonts:
        - asset: fonts/Roboto/RobotoMono-Regular.ttf
    - family: NotoEmoji
      fonts:
        - asset: fonts/NotoEmoji/NotoColorEmoji.ttf
    - family: Inter
      fonts:
        - asset: fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter/Inter-Black.ttf
          weight: 900

msix_config:
  display_name: FluffyChat
  publisher_display_name: FluffyChat
  publisher: CN=FluffyChat, O=Head of bad integration tests, L=Matrix, S=Internet, C=EU
  identity_name: chat.fluffy.fluffychat
  logo_path: assets\logo.png
  capabilities: internetClient, location, microphone, webcam
  protocol_activation: https
  app_uri_handler_hosts: fluffychat.im, matrix.to
  execution_alias: fluffychat
  sign_msix: false
  install_certificate: false

dependency_overrides:
  # Until all dependencies are compatible. Missing: file_picker_cross, flutter_matrix_html
  ffi: ^2.0.0
  # This otherwise breaks on linux with flutter 3.7.0, let's override it for now.
  file_selector: ^0.9.2+2
  file_selector_linux: ^0.9.1
  flutter_svg: ^2.0.4
  # fake secure storage plugin for Windows
  # See: https://gitlab.com/gitlab-com/gl-infra/reliability/-/issues/15161
  flutter_secure_storage_windows:
    git:
      url: https://gitlab.com/TheOneWithTheBraid/flutter_secure_storage_windows.git
      ref: main
  geolocator_android:
    hosted:
      name: geolocator_android
      url: https://hanntech-gmbh.gitlab.io/free2pass/flutter-geolocator-floss
  # waiting for null safety
  # Upstream pull request: https://github.com/AntoineMarcel/keyboard_shortcuts/pull/13
  keyboard_shortcuts:
    git:
      url: https://github.com/TheOneWithTheBraid/keyboard_shortcuts.git
      ref: null-safety

cider:
  link_template:
    tag: https://github.com/linagora/twake-on-matrix/releases/tag/%tag% # initial release link template
